2020-11-09 06:20:34,652 [MainThread  ] [INFO ] [django.utils.autorel]  Watching for file changes with StatReloader
2020-11-09 06:21:02,640 [Thread-1    ] [INFO ] [django.server       ]  "GET /api/ HTTP/1.1" 200 5312
2020-11-09 06:21:02,694 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
2020-11-09 06:21:02,703 [Thread-2    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2020-11-09 06:21:02,703 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2020-11-09 06:21:02,704 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
2020-11-09 06:21:02,704 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
2020-11-09 06:21:02,705 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
2020-11-09 06:21:02,709 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
2020-11-09 06:21:02,713 [Thread-2    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
2020-11-09 06:21:02,714 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
2020-11-09 06:21:02,714 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
2020-11-09 06:21:02,720 [Thread-3    ] [WARNI] [django.request      ]  Not Found: /static/rest_framework/css/bootstrap.min.css.map
2020-11-09 06:21:02,720 [Thread-3    ] [WARNI] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 2299
2020-11-09 06:21:02,750 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
2020-11-09 06:21:08,383 [Thread-1    ] [INFO ] [django.server       ]  "GET /api/reservations HTTP/1.1" 301 0
2020-11-09 06:21:08,400 [Thread-1    ] [WARNI] [django.request      ]  Unauthorized: /api/reservations/
2020-11-09 06:21:08,400 [Thread-1    ] [WARNI] [django.server       ]  "GET /api/reservations/ HTTP/1.1" 401 5235
2020-11-09 06:21:08,456 [Thread-2    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2020-11-09 06:21:08,456 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2020-11-09 06:21:08,456 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
2020-11-09 06:21:08,456 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2020-11-09 06:21:08,457 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2020-11-09 06:21:08,457 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2020-11-09 06:21:08,460 [Thread-2    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2020-11-09 06:21:08,460 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2020-11-09 06:21:08,461 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2020-11-09 06:21:08,461 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2020-11-09 06:21:08,483 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2020-11-09 06:21:08,491 [Thread-1    ] [WARNI] [django.request      ]  Not Found: /static/rest_framework/css/bootstrap.min.css.map
2020-11-09 06:21:08,491 [Thread-1    ] [WARNI] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 2299
2020-11-09 06:21:08,505 [Thread-7    ] [WARNI] [django.request      ]  Not Found: /favicon.ico
2020-11-09 06:21:08,505 [Thread-7    ] [WARNI] [django.server       ]  "GET /favicon.ico HTTP/1.1" 404 2191
2020-11-09 06:21:25,224 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:27:44,471 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:28:46,882 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:28:53,389 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:29:15,500 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:29:42,583 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:29:47,842 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:29:53,606 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:30:04,687 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:30:21,181 [MainThread  ] [INFO ] [django.utils.autorel]  Watching for file changes with StatReloader
2020-11-09 06:30:34,336 [Thread-1    ] [WARNI] [django.request      ]  Unauthorized: /api/reservations/
2020-11-09 06:30:34,337 [Thread-1    ] [WARNI] [django.server       ]  "GET /api/reservations/ HTTP/1.1" 401 5235
2020-11-09 06:30:34,390 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2020-11-09 06:30:34,396 [Thread-2    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2020-11-09 06:30:34,398 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
2020-11-09 06:30:34,401 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2020-11-09 06:30:34,401 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2020-11-09 06:30:34,401 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2020-11-09 06:30:34,402 [Thread-2    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2020-11-09 06:30:34,403 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2020-11-09 06:30:34,403 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2020-11-09 06:30:34,404 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2020-11-09 06:30:34,410 [Thread-2    ] [WARNI] [django.request      ]  Not Found: /static/rest_framework/css/bootstrap.min.css.map
2020-11-09 06:30:34,411 [Thread-2    ] [WARNI] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 2299
2020-11-09 06:30:34,433 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2020-11-09 06:30:48,425 [Thread-7    ] [INFO ] [django.server       ]  "GET /api/reservations/ HTTP/1.1" 200 2
2020-11-09 06:31:54,425 [Thread-8    ] [INFO ] [django.server       ]  code 400, message Bad request syntax ('\x16\x03\x01\x00å\x01\x00\x00á\x03\x03ìo×')
2020-11-09 06:31:54,425 [Thread-8    ] [ERROR] [django.server       ]  You're accessing the development server over HTTPS, but it only supports HTTP.

2020-11-09 06:32:01,542 [Thread-9    ] [INFO ] [django.server       ]  code 400, message Bad request version ('À\x13À')
2020-11-09 06:32:01,542 [Thread-9    ] [ERROR] [django.server       ]  You're accessing the development server over HTTPS, but it only supports HTTP.

2020-11-09 06:32:07,768 [Thread-7    ] [WARNI] [django.request      ]  Not Found: /api/registrations/
2020-11-09 06:32:07,769 [Thread-7    ] [WARNI] [django.server       ]  "POST /api/registrations/ HTTP/1.1" 404 3350
2020-11-09 06:32:16,588 [Thread-7    ] [ERROR] [django.request      ]  Internal Server Error: /api/reservations/
Traceback (most recent call last):
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/shaheermirza/Development/Revitii/solsticesociety/backend/api/views.py", line 25, in create
    send_mail(
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
2020-11-09 06:32:16,590 [Thread-7    ] [ERROR] [django.server       ]  "POST /api/reservations/ HTTP/1.1" 500 19209
2020-11-09 06:33:15,631 [MainThread  ] [INFO ] [django.utils.autorel]  /Users/shaheermirza/Development/Revitii/solsticesociety/backend/settings.py changed, reloading.
2020-11-09 06:33:15,632 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:33:16,058 [MainThread  ] [INFO ] [django.utils.autorel]  Watching for file changes with StatReloader
2020-11-09 06:35:29,485 [MainThread  ] [INFO ] [django.utils.autorel]  /Users/shaheermirza/Development/Revitii/solsticesociety/backend/settings.py changed, reloading.
2020-11-09 06:35:29,486 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:35:29,968 [MainThread  ] [INFO ] [django.utils.autorel]  Watching for file changes with StatReloader
2020-11-09 06:35:32,200 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /api/reservations/
Traceback (most recent call last):
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/shaheermirza/Development/Revitii/solsticesociety/backend/api/views.py", line 25, in create
    send_mail(
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 871, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (550, b'Unauthenticated senders not allowed', 'shaheermirzacs@gmail.com')
2020-11-09 06:35:32,201 [Thread-1    ] [ERROR] [django.server       ]  "POST /api/reservations/ HTTP/1.1" 500 18638
2020-11-09 06:38:18,236 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /api/reservations/
Traceback (most recent call last):
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/shaheermirza/Development/Revitii/solsticesociety/backend/api/views.py", line 25, in create
    send_mail(
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/Users/shaheermirza/.local/share/virtualenvs/solsticesociety-SaBv4jx5/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 871, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (550, b'Unauthenticated senders not allowed', 'shaheermirzacs@gmail.com')
2020-11-09 06:38:18,237 [Thread-1    ] [ERROR] [django.server       ]  "POST /api/reservations/ HTTP/1.1" 500 18638
2020-11-09 06:49:53,404 [MainThread  ] [INFO ] [django.utils.autorel]  /Users/shaheermirza/Development/Revitii/solsticesociety/backend/api/views.py changed, reloading.
2020-11-09 06:49:53,404 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:49:53,849 [MainThread  ] [INFO ] [django.utils.autorel]  Watching for file changes with StatReloader
2020-11-09 06:49:59,238 [Thread-1    ] [INFO ] [django.server       ]  "POST /api/reservations/ HTTP/1.1" 201 194
2020-11-09 06:50:05,038 [Thread-1    ] [INFO ] [django.server       ]  "GET /api/reservations/ HTTP/1.1" 200 925
2020-11-09 06:52:40,480 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
2020-11-09 06:52:40,549 [MainThread  ] [DEBUG] [asyncio             ]  Using selector: KqueueSelector
